// @generated by web/scripts/gen-native-oauth-allowlist.ts — DO NOT EDIT BY HAND.
//
// Source of truth: web/src/lib/mcp-providers.ts (MCP_PROVIDERS). Each tuple is
// (MCP-server origin, exact OAuth authorization-server origins that provider
// may advertise through /.well-known/oauth-protected-resource). The refresh
// path in native_oauth.rs aborts when a discovered endpoint's origin is not in
// this list — see the Dialed regression for why.
//
// Regenerate after ANY catalog change that touches mcpServerUrl or
// oauthAuthorizationServerOrigins:
//
//     cd web && npm run gen:allowlist
//
// CI enforcement: web/src/lib/mcp-providers.allowlist-sync.test.ts fails when
// this file is stale.

#[rustfmt::skip]
pub(crate) const NATIVE_MCP_OAUTH_ALLOWLIST: &[(&str, &[&str])] = &[
    ("https://mcp.attio.com", &["https://app.attio.com"]), // attio
    ("https://mcp.usepylon.com", &["https://o.auth.usepylon.com"]), // pylon
    ("https://mcp.hubspot.com", &["https://mcp.hubspot.com"]), // hubspot
    ("https://api.fathom.ai", &["https://api.fathom.ai", "https://fathom.video"]), // fathom
    ("https://dialed.day", &["https://dialed.day"]), // dialed
    ("https://mcp.linear.app", &["https://mcp.linear.app"]), // linear
    ("https://mcp.amplemarket.com", &["https://app.amplemarket.com"]), // amplemarket
    ("https://api.clay.com", &["https://api.clay.com", "https://app.clay.com"]), // clay
    ("https://mcp.avoma.com", &["https://prod-api.avoma.com"]), // avoma
    ("https://gmailmcp.googleapis.com", &["https://accounts.google.com", "https://oauth2.googleapis.com"]), // gmail
    ("https://mcp.notion.com", &["https://mcp.notion.com"]), // notion
    ("https://mcp.intercom.com", &["https://mcp.intercom.com"]), // intercom
    ("https://mcp.atlassian.com", &["https://mcp.atlassian.com", "https://cf.mcp.atlassian.com"]), // atlassian
    ("https://mcp.asana.com", &["https://mcp.asana.com"]), // asana
    ("https://mcp.monday.com", &["https://mcp.monday.com"]), // monday
    ("https://mcp.api.getguru.com", &["https://mcp.api.getguru.com"]), // guru
    ("https://api.fireflies.ai", &["https://api.fireflies.ai"]), // fireflies
    ("https://mcp.amplitude.com", &["https://mcp.amplitude.com"]), // amplitude
    ("https://mcp.apollo.io", &["https://mcp.apollo.io"]), // apollo
    ("https://mcp.posthog.com", &["https://oauth.posthog.com"]), // posthog
    ("https://mcp.stripe.com", &["https://access.stripe.com", "https://mcp.stripe.com"]), // stripe
    ("https://mcp.vercel.com", &["https://mcp.vercel.com", "https://vercel.com"]), // vercel
    ("https://mcp.canva.com", &["https://mcp.canva.com"]), // canva
    ("https://mcp.clickup.com", &["https://mcp.clickup.com"]), // clickup
    ("https://mcp.close.com", &["https://mcp.close.com", "https://api.close.com", "https://app.close.com"]), // close
    ("https://mcp.sentry.dev", &["https://mcp.sentry.dev"]), // sentry
    ("https://mcp.mixpanel.com", &["https://mcp.mixpanel.com", "https://mixpanel.com"]), // mixpanel
    ("https://mcp.granola.ai", &["https://mcp.granola.ai", "https://mcp-auth.granola.ai"]), // granola
    ("https://mcp.dropbox.com", &["https://mcp.dropbox.com", "https://www.dropbox.com", "https://api.dropboxapi.com"]), // dropbox
    ("https://mcp.webflow.com", &["https://mcp.webflow.com"]), // webflow
    ("https://mcp.cloudflare.com", &["https://mcp.cloudflare.com"]), // cloudflare
    ("https://mcp.neon.tech", &["https://mcp.neon.tech"]), // neon
    ("https://mcp.cal.com", &["https://mcp.cal.com"]), // cal
    ("https://mcp.klaviyo.com", &["https://mcp.klaviyo.com"]), // klaviyo
    ("https://mcp.paypal.com", &["https://mcp.paypal.com"]), // paypal
    ("https://mcp.squareup.com", &["https://mcp.squareup.com"]), // square
    ("https://mcp.airtable.com", &["https://mcp.airtable.com", "https://airtable.com"]), // airtable
    ("https://mcp.railway.app", &["https://mcp.railway.app", "https://backboard.railway.com"]), // railway
    ("https://mcp.resend.com", &["https://mcp.resend.com", "https://api.resend.com"]), // resend
    ("https://app.hex.tech", &["https://app.hex.tech", "https://auth.app.hex.tech"]), // hex
    ("https://app.pendo.io", &["https://app.pendo.io"]), // pendo
    ("https://mcp.similarweb.com", &["https://mcp.similarweb.com", "https://mcp-auth.similarweb.com"]), // similarweb
    ("https://mcp.datadoghq.com", &["https://mcp.datadoghq.com", "https://app.datadoghq.com"]), // datadog
    ("https://mcp.commonroom.io", &["https://mcp.commonroom.io", "https://login.commonroom.io"]), // commonroom
    ("https://mcp.gong.io", &["https://mcp.gong.io", "https://app.gong.io"]), // gong
    ("https://mcp.box.com", &["https://mcp.box.com", "https://api.box.com", "https://account.box.com"]), // box
    ("https://mcp.pagerduty.com", &["https://mcp.pagerduty.com", "https://app.pagerduty.com"]), // pagerduty
    ("https://mcp.slack.com", &["https://mcp.slack.com", "https://slack.com"]), // slack
    ("https://mcp.zoom.us", &["https://zoom.us", "https://mcp.zoom.us", "https://mcp-us.zoom.us"]), // zoom
    ("https://api.outreach.io", &["https://api.outreach.io"]), // outreach
    ("https://mcp.salesloft.com", &["https://accounts.salesloft.com", "https://mcp.salesloft.com"]), // salesloft
    ("https://mcp.zoominfo.com", &["https://mcp.zoominfo.com", "https://okta-login.zoominfo.com"]), // zoominfo
    ("https://mcp.lusha.com", &["https://auth.lusha.com"]), // lusha
    ("https://mcp.hunter.io", &["https://hunter.io"]), // hunter
    ("https://mcp.instantly.ai", &["https://api.instantly.ai"]), // instantly
    ("https://mcp.crossbeam.com", &["https://mcp.crossbeam.com"]), // crossbeam
    ("https://mcp.api.harmonic.ai", &["https://mcp.api.harmonic.ai"]), // harmonic
    ("https://fire.chilipiper.com", &["https://fire.chilipiper.com"]), // chilipiper
    ("https://day.ai", &["https://day.ai"]), // dayai
    ("https://api.clarify.ai", &["https://auth1.clarify.ai"]), // clarify
    ("https://mcp.staircase.ai", &["https://mcp.staircase.ai"]), // staircase
    ("https://mcp.zendesk.com", &["https://mcp.zendesk.com"]), // zendesk
    ("https://mcp.helpscout.net", &["https://mcp.helpscout.net"]), // helpscout
    ("https://mcp.gorgias.com", &["https://mcp.gorgias.com"]), // gorgias
    ("https://mcp.plain.com", &["https://signin.auth.plain.com"]), // plain
    ("https://api.lorikeetcx.ai", &["https://api.lorikeetcx.ai", "https://app.lorikeetcx.ai"]), // lorikeet
    ("https://app.unthread.io", &["https://app.unthread.io"]), // unthread
    ("https://wisdom-api.enterpret.com", &["https://oauth.enterpret.com"]), // enterpret
    ("https://dovetail.com", &["https://auth.dovetail.com"]), // dovetail
    ("https://mcp.missiveapp.com", &["https://auth.missiveapp.com"]), // missive
    ("https://mcp.otter.ai", &["https://otter.ai"]), // otter
    ("https://api.grain.com", &["https://api.grain.com", "https://grain.com"]), // grain
    ("https://mcp.krisp.ai", &["https://api.krisp.ai", "https://mcp.krisp.ai"]), // krisp
    ("https://app.circleback.ai", &["https://app.circleback.ai"]), // circleback
    ("https://mcp.tldv.io", &["https://keycloak.tldv.io"]), // tldv
    ("https://mcp.ramp.com", &["https://api.ramp.com", "https://mcp.ramp.com"]), // ramp
    ("https://api.brex.com", &["https://accounts-api.brex.com", "https://api.brex.com"]), // brex
    ("https://mcp.mercury.com", &["https://mcp.mercury.com"]), // mercury
    ("https://mcp.expensify.com", &["https://www.expensify.com"]), // expensify
    ("https://mcp.navan.com", &["https://login.navan.com"]), // navan
    ("https://mcp.app.carta.com", &["https://mcp.app.carta.com"]), // carta
    ("https://api.digits.com", &["https://api.digits.com"]), // digits
    ("https://mcp.gocardless.com", &["https://mcp.gocardless.com"]), // gocardless
    ("https://mcp.mercadopago.com", &["https://auth.mercadopago.com", "https://mcp.mercadopago.com"]), // mercadopago
    ("https://premium.mcp.pitchbook.com", &["https://premium.mcp.pitchbook.com"]), // pitchbook
    ("https://mcp.morningstar.com", &["https://mcp.morningstar.com"]), // morningstar
    ("https://mcp.cbinsights.com", &["https://mcp.cbinsights.com"]), // cbinsights
    ("https://mcp.quartr.com", &["https://mcp.quartr.com"]), // quartr
    ("https://mcp.daloopa.com", &["https://mcp.daloopa.com"]), // daloopa
    ("https://mcp.consensus.app", &["https://consensus.app"]), // consensus
    ("https://mcp.api.gusto.com", &["https://mcp.api.gusto.com"]), // gusto
    ("https://api.letsdeel.com", &["https://api.letsdeel.com"]), // deel
    ("https://mcp.ashbyhq.com", &["https://mcp-auth.ashbyhq.com"]), // ashby
    ("https://mcp.workable.com", &["https://mcp.workable.com", "https://workable.com"]), // workable
    ("https://mcp.metaview.ai", &["https://auth.metaview.ai"]), // metaview
    ("https://mcp.indeed.com", &["https://apis.indeed.com", "https://secure.indeed.com"]), // indeed
    ("https://api.udemy.com", &["https://api.udemy.com"]), // udemy
    ("https://mcp-server.signnow.com", &["https://mcp-server.signnow.com"]), // signnow
    ("https://mcp.vanta.com", &["https://api.vanta.com", "https://app.vanta.com", "https://mcp.vanta.com"]), // vanta
    ("https://mcp.drata.com", &["https://drata-prod.us.auth0.com", "https://mcp.drata.com"]), // drata
    ("https://mcp.figma.com", &["https://api.figma.com", "https://www.figma.com"]), // figma
    ("https://mcp.miro.com", &["https://mcp.miro.com"]), // miro
    ("https://mcp.lucid.app", &["https://mcp.lucid.app"]), // lucid
    ("https://mcp.productboard.com", &["https://mcp.productboard.com"]), // productboard
    ("https://mcp.aha.io", &["https://mcp.aha.io"]), // aha
    ("https://mcp.shortcut.com", &["https://api.app.shortcut.com"]), // shortcut
    ("https://ai.todoist.net", &["https://todoist.com"]), // todoist
    ("https://mcp.ai.teamwork.com", &["https://teamwork.com", "https://www.teamwork.com"]), // teamwork
    ("https://mcp.calendly.com", &["https://calendly.com"]), // calendly
    ("https://mcp.mail.superhuman.com", &["https://mcp.auth.mail.superhuman.com"]), // superhuman
    ("https://mcp.craft.do", &["https://mcp.craft.do"]), // craft
    ("https://mcp.mem.ai", &["https://api.mem.ai", "https://mem.ai"]), // mem
    ("https://mcp.gamma.app", &["https://auth.gamma.app"]), // gamma
    ("https://mcp.pitch.com", &["https://auth.pitch.com"]), // pitch
    ("https://app.eraser.io", &["https://app.eraser.io"]), // eraser
    ("https://mcp.jotform.com", &["https://oauth2.jotform.com"]), // jotform
    ("https://api.typeform.com", &["https://admin.typeform.com", "https://api.typeform.com"]), // typeform
    ("https://mcp.surveymonkey.com", &["https://mcp.surveymonkey.com"]), // surveymonkey
    ("https://mcp-server.egnyte.com", &["https://mcp-oauth.egnyte.com"]), // egnyte
    ("https://ai-inc.mailchimp.com", &["https://ai-inc.mailchimp.com"]), // mailchimp
    ("https://mcp.customer.io", &["https://mcp.customer.io"]), // customerio
    ("https://api.ahrefs.com", &["https://ahrefs.com", "https://api.ahrefs.com", "https://app.ahrefs.com"]), // ahrefs
    ("https://mcp.semrush.com", &["https://api.semrush.com", "https://oauth.semrush.com"]), // semrush
    ("https://asset-management.mcp.cloudinary.com", &["https://asset-management.mcp.cloudinary.com"]), // cloudinary
    ("https://mcp.contentful.com", &["https://mcp.contentful.com"]), // contentful
    ("https://mcp.sanity.io", &["https://mcp.sanity.io"]), // sanity
    ("https://mcp.wix.com", &["https://mcp.wix.com"]), // wix
    ("https://public-api.wordpress.com", &["https://public-api.wordpress.com"]), // wordpress
    ("https://mcp.gitbook.com", &["https://oauth.gitbook.com"]), // gitbook
    ("https://mcp.mintlify.com", &["https://mcp.mintlify.com"]), // mintlify
    ("https://mcp.deepl.com", &["https://mcp.deepl.com"]), // deepl
    ("https://gitlab.com", &["https://gitlab.com"]), // gitlab
    ("https://mcp.supabase.com", &["https://api.supabase.com"]), // supabase
    ("https://netlify-mcp.netlify.app", &["https://netlify-mcp.netlify.app"]), // netlify
    ("https://mcp.heroku.com", &["https://mcp.heroku.com"]), // heroku
    ("https://mcp.buildkite.com", &["https://mcp.buildkite.com"]), // buildkite
    ("https://mcp.grafana.com", &["https://mcp.grafana.com"]), // grafana
    ("https://mcp.newrelic.com", &["https://login.newrelic.com", "https://mcp.newrelic.com"]), // newrelic
    ("https://mcp.honeycomb.io", &["https://ui.honeycomb.io"]), // honeycomb
    ("https://mcp.incident.io", &["https://app.incident.io", "https://mcp.incident.io"]), // incidentio
    ("https://mcp.rootly.com", &["https://rootly.com"]), // rootly
    ("https://bugsnag.mcp.smartbear.com", &["https://oauth.bugsnag.com"]), // bugsnag
    ("https://mcp.launchdarkly.com", &["https://app.launchdarkly.com", "https://mcp.launchdarkly.com"]), // launchdarkly
    ("https://mcp.pscale.dev", &["https://app.planetscale.com", "https://auth.planetscale.com", "https://mcp.pscale.dev"]), // planetscale
    ("https://mcp.prisma.io", &["https://auth.prisma.io", "https://mcp.prisma.io"]), // prisma
    ("https://mcp.instantdb.com", &["https://mcp.instantdb.com"]), // instantdb
    ("https://mcp.algolia.com", &["https://dashboard.algolia.com"]), // algolia
    ("https://api.statsig.com", &["https://api.statsig.com"]), // statsig
    ("https://mcp.postman.com", &["https://mcp.postman.com"]), // postman
    ("https://mcp.semgrep.ai", &["https://login.semgrep.dev"]), // semgrep
    ("https://mcp.workos.com", &["https://signin.workos.com"]), // workos
    ("https://mcp.stytch.dev", &["https://rustic-kilogram-6347.customers.stytch.com", "https://stytch.com"]), // stytch
    ("https://mcp.mux.com", &["https://auth.mux.com"]), // mux
    ("https://mcp.knock.app", &["https://mcp.knock.app"]), // knock
    ("https://mcp.lovable.dev", &["https://lovable.dev"]), // lovable
    ("https://mcp.retool.com", &["https://mcp.retool.com"]), // retool
    ("https://api.telnyx.com", &["https://api.telnyx.com"]), // telnyx
    ("https://mcp.jam.dev", &["https://api.jam.dev"]), // jam
    ("https://mcp.globalping.dev", &["https://mcp.globalping.dev"]), // globalping
    ("https://mcp.airbyte.ai", &["https://mcp.airbyte.ai"]), // airbyte
    ("https://api.motherduck.com", &["https://mcp-auth.motherduck.com"]), // motherduck
    ("https://integrations.getmontecarlo.com", &["https://auth.getmontecarlo.com"]), // montecarlo
    ("https://mcp.atlan.com", &["https://mcp.atlan.com"]), // atlan
    ("https://huggingface.co", &["https://huggingface.co"]), // huggingface
    ("https://mcp.zapier.com", &["https://mcp.zapier.com"]), // zapier
    ("https://mcp.make.com", &["https://www.make.com"]), // make
    ("https://ifttt.com", &["https://ifttt.com"]), // ifttt
    ("https://mcp.exa.ai", &["https://auth.exa.ai"]), // exa
    ("https://mcp.tavily.com", &["https://mcp.tavily.com"]), // tavily
    ("https://mcp.firecrawl.dev", &["https://www.firecrawl.dev"]), // firecrawl
    ("https://mcp.apify.com", &["https://console-backend.apify.com", "https://console.apify.com"]), // apify
    ("https://mcp.brightdata.com", &["https://brightdata.com"]), // brightdata
    ("https://mcp.onkernel.com", &["https://mcp.onkernel.com"]), // kernel
    ("https://mcp.docusign.com", &["https://account.docusign.com", "https://mcp.docusign.com"]), // docusign
    ("https://mcp.xero.com", &["https://identity.xero.com", "https://login.xero.com"]), // xero
    ("https://mcp.frontapp.com", &["https://app.frontapp.com"]), // front
    ("https://mcp.smartsheet.com", &["https://api.smartsheet.com", "https://app.smartsheet.com", "https://mcp.smartsheet.com"]), // smartsheet
    ("https://mcp.mongodb.com", &["https://authorize.mongodb.com", "https://cloud.mongodb.com"]), // mongodb
    ("https://mcp.circleci.com", &["https://app.circleci.com", "https://circleci.com", "https://mcp.circleci.com"]), // circleci
    ("https://mcp.chargebee.com", &["https://app.chargebee.com"]), // chargebee
    ("https://bigquery.googleapis.com", &["https://accounts.google.com", "https://oauth2.googleapis.com"]), // bigquery
    ("https://mcp.na1.ironcladapp.com", &["https://ironcladapp.com"]), // ironclad
    ("https://api.harvey.ai", &["https://api.harvey.ai", "https://harvey-ai.us.auth0.com"]), // harvey
    ("https://mcp.tableau.com", &["https://sso.online.tableau.com"]), // tableau
    ("https://setup.shopify.com", &["https://setup.shopify.com"]), // shopify
];
