#!/usr/bin/env bash
#
# One command to get Tembo Agent Studio running — built for a Tembo sandbox
# (Docker + Docker Compose are preinstalled) but works on any Docker host.
#
#   ./scripts/dev-up.sh
#
# It:
#   1. writes a .env (first run only) with random secrets and NO OAuth, so the
#      login screen uses email + password (the zero-config quickstart),
#   2. boots Postgres + api + web via Docker Compose,
#   3. waits for the web app, then seeds an instance-admin account you can sign
#      in with immediately.
#
# Re-runnable: an existing .env is reused and a seeded admin is left as-is.
# Override the seed creds with SEED_ADMIN_EMAIL / SEED_ADMIN_PASSWORD.
set -euo pipefail

cd "$(dirname "$0")/.."

ADMIN_EMAIL="${SEED_ADMIN_EMAIL:-admin@tembo.local}"
ADMIN_PASSWORD="${SEED_ADMIN_PASSWORD:-tembo-dev-password}"
ORIGIN="${BETTER_AUTH_URL:-http://localhost:3000}"

# 1. .env — generated once. Random secrets; INSTANCE_ADMIN_EMAILS bootstraps the
#    first admin; no OAuth vars → email/password sign-in turns on automatically.
if [ ! -f .env ]; then
  echo "→ writing .env (email/password auth, admin = $ADMIN_EMAIL)"
  cat > .env <<EOF
# Generated by scripts/dev-up.sh — dev/sandbox only, do not use in production.
POSTGRES_USER=tas
POSTGRES_PASSWORD=tas
POSTGRES_DB=tas
BETTER_AUTH_SECRET=$(openssl rand -base64 32)
TAS_ENCRYPTION_KEY=$(openssl rand -base64 32)
INTERNAL_API_TOKEN=$(openssl rand -base64 32)
BETTER_AUTH_URL=$ORIGIN
TAS_INSTANCE_NAME=Tembo Agent Studio (dev)
INSTANCE_ADMIN_EMAILS=$ADMIN_EMAIL
EOF
else
  echo "→ reusing existing .env"
fi

# 2. boot the stack (build from source; api migrations apply on boot)
echo "→ docker compose up (building images on first run can take a few minutes)…"
docker compose up -d --build

# 3. wait for the web app to answer
echo -n "→ waiting for $ORIGIN "
until curl -fsS -o /dev/null "$ORIGIN" 2>/dev/null; do
  echo -n "."
  sleep 3
done
echo " up"

# 4. seed the admin account via better-auth email/password sign-up. The
#    sign-up gate defaults to invite-only (INSTANCE_ADMIN_EMAILS / invited emails), so
#    this works for the admin above and nobody else.
echo "→ seeding admin account $ADMIN_EMAIL"
code=$(curl -s -o /dev/null -w '%{http_code}' -X POST "$ORIGIN/api/auth/sign-up/email" \
  -H 'content-type: application/json' \
  -d "{\"email\":\"$ADMIN_EMAIL\",\"password\":\"$ADMIN_PASSWORD\",\"name\":\"Tembo Admin\"}" || true)
case "$code" in
  2*) echo "   created" ;;
  4*) echo "   already exists (or gated) — reuse your existing password" ;;
  *)  echo "   couldn't reach auth endpoint (HTTP $code) — the web app may still be starting" ;;
esac

cat <<EOF

✅ Tembo Agent Studio is up
   App:        $ORIGIN
   API health: http://localhost:8080/health
   Sign in:    $ADMIN_EMAIL  /  $ADMIN_PASSWORD

Next: sign in → create a workspace. The bundled sample agents (./agents) show up
automatically with no repo connected; connect a GitHub repo (with a PAT) to load
your own. Stop everything with:  docker compose down
EOF
